### PR TITLE
PHP < 5.4 Support

### PR DESCRIPTION
**Pull request by Dayjo**
Hi @slushie ,

Thanks for this, it's super useful, there doesn't seem to be any documentation from Google anywhere in regards to doing this. Life saver! 

I've changed the class to have long array syntax as I needed some PHP support for 5.3.3 - Don't know if you want to merge this so that it's just fully supportive, or just run it as a secondary branch, up to you.

Cheers

### CODE REVIEW

**Comment by slushie** [comment]
Thanks! I'm going to change the version requirement in composer.json as well. I think that should cover everything and make it fully compatible with 5.3.x

**Comment by Dayjo** [comment]
Great, in which case I may use composer to load it in too. :+1:

**Comment by Dayjo** [comment]
@slushie - noticed you updated the requirements, but still seems to only have the previous version on packagist. Do you need to manually push the update to them or something? (not actually sure how all that works)

**Comment by slushie** [comment]
Oh, you’re right! I just marked the Packagist page for update, so it should be available now. Sorry about that!

**Comment by Dayjo** [comment]
No problemo! Great stuff, thanks!

**Pull request merged**
